const style = document.createElement('style');
style.innerHTML = `
  body {
    background-image: linear-gradient(180deg, #1B6A8E 0%, #70A1B7 100%);
    background-attachment: fixed;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    color: #2d3748;
    margin: 0;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
    padding: 1rem; 
    box-sizing: border-box;
  }
  
  .jspsych-content-wrapper, .jspsych-content {
    background: #ffffff;
    padding: 1.5rem;
    border-radius: 16px;
    box-shadow: 0 10px 25px rgba(0, 0, 0, 0.05);
    max-width: 750px;
    width: 100%;
    box-sizing: border-box;
  }

  @media(min-width: 768px) {
    .jspsych-content-wrapper, .jspsych-content {
      padding: 2.5rem;
    }
  }
  
  h2 {
    color: #1a202c;
    font-size: 1.35rem;
    font-weight: 700;
    margin-bottom: 1.5rem;
  }
  @media(min-width: 768px) {
    h2 { font-size: 1.8rem; }
  }

  p, .trial-text {
    font-size: 0.95rem;
    line-height: 1.5;
    color: #4a5568;
    margin-bottom: 1.2rem;
  }
  @media(min-width: 768px) {
    p, .trial-text { 
      font-size: 1.1rem; 
      line-height: 1.6;
    }
  }

  .experiment-graph-container {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 100%; 
    max-width: 550px; 
    margin: 1rem auto;
    border-radius: 8px;
    border: 1px solid #e2e8f0;
    padding: 8px;
    background: #fdfdfd;
    box-shadow: inset 0 2px 4px rgba(0,0,0,0.02);
    box-sizing: border-box;
  }

  .experiment-graph {
    width: 100%;
    max-height: 40vh;
    height: auto; 
    object-fit: contain; 
    display: block;
  }

  /* Target ONLY the wrapper generated by the button-response choice screens */
  #jspsych-html-button-response-btngroup,
  .jspsych-btn-group {
    display: flex !important;
    flex-direction: column !important; 
    align-items: center !important;
    justify-content: center !important;
    width: 100% !important;
    max-width: 380px !important;
    margin: 1.5rem auto 0 auto !important;
    gap: 0.5rem !important;
  }

  /* Universal button cosmetic styling */
  .jspsych-btn {
    background-color: #3182ce !important;
    color: white !important;
    border: none !important;
    border-radius: 8px !important;
    font-size: 0.95rem !important;
    font-weight: 600 !important;
    cursor: pointer !important;
    transition: background-color 0.2s ease, transform 0.1s ease !important;
    box-shadow: 0 4px 6px rgba(49, 130, 206, 0.15) !important;
    box-sizing: border-box !important;
  }

  /* Apply full-width block behaviors ONLY to multi-choice screens on mobile */
  #jspsych-html-button-response-btngroup .jspsych-btn,
  .jspsych-btn-group .jspsych-btn {
    display: block !important;
    width: 100% !important; 
    max-width: 100% !important;
    margin: 0 !important; 
    padding: 12px 20px !important; 
  }

  /* Slider single button behavior styling (Leaves alignment to native plugin constraints) */
  #jspsych-html-slider-response-next.jspsych-btn,
  #jspsych-html-slider-response-btngroup .jspsych-btn {
    display: inline-block !important;
    width: auto !important;
    min-width: 150px;
    padding: 12px 32px !important;
    margin: 2rem auto 0 auto !important;
  }

  /* Desktop overrides for choice screen layout buttons */
  @media(min-width: 768px) {
    #jspsych-html-button-response-btngroup,
    .jspsych-btn-group {
      flex-direction: row !important;
      max-width: 100% !important;
      gap: 0 !important;
    }
    #jspsych-html-button-response-btngroup .jspsych-btn,
    .jspsych-btn-group .jspsych-btn {
      display: inline-block !important;
      width: auto !important;
      margin: 0.5rem !important;
      font-size: 1rem !important;
      padding: 12px 24px !important;
    }
    #jspsych-html-slider-response-next.jspsych-btn {
      font-size: 1rem !important;
    }
  }

  .jspsych-btn:hover {
    background-color: #2b6cb0 !important;
    transform: translateY(-1px);
    box-shadow: 0 6px 12px rgba(49, 130, 206, 0.2) !important;
  }

  .jspsych-btn:active {
    transform: translateY(1px);
  }

  .jspsych-sliders-container {
    margin: 1.5rem 0 !important;
  }
  
  input[type=range].jspsych-slider {
    -webkit-appearance: none;
    width: 100%;
    margin: 10px 0;
    background: transparent;
  }
  
  input[type=range].jspsych-slider:focus {
    outline: none;
  }
  
  input[type=range].jspsych-slider::-webkit-slider-runnable-track {
    width: 100%;
    height: 8px;
    cursor: pointer;
    background: #e2e8f0;
    border-radius: 4px;
  }
  
  input[type=range].jspsych-slider::-webkit-slider-thumb {
    height: 20px;
    width: 20px;
    border-radius: 50%;
    background: #3182ce;
    cursor: pointer;
    -webkit-appearance: none;
    margin-top: -6px;
    box-shadow: 0 2px 4px rgba(0,0,0,0.2);
    transition: background-color 0.1s;
  }

  input[type=range].jspsych-slider::-webkit-slider-thumb:hover {
    background: #2b6cb0;
  }

  .jspsych-slider-labels span {
    font-size: 0.75rem !important;
    color: #718096 !important;
    font-weight: 500;
  }
  @media(min-width: 768px) {
    .jspsych-slider-labels span { font-size: 0.85rem !important; }
  }
`;
document.head.appendChild(style);


const jsPsych = initJsPsych({

  on_finish: function() {

    if (typeof cognition_run_finish === "function") {

      cognition_run_finish();

    }

  }

});



let timeline = [];



// Welcome Screen

const welcome = {

  type: jsPsychHtmlButtonResponse,

  stimulus: `

  <h2>Welcome to this Study</h2>

  <p>In this task, you will be presented with real-life scenarios paired with a relevant graph.</p>

  <p>You will be asked to make a decision based on specific criteria and the provided graph.</p>

  <p>Please make your choice as quickly and accurately as possible, then state your confidence.</p>

  `,

  choices: ['Start Experiment']

};

timeline.push(welcome);



// Define Scenarios

const experimental_trials = [

  {

    sentence: "You are planning a career move abroad: which country should you avoid based on workplace safety?",

    graph_pool: ["SimpleHonestWork.png", "SimpleDishonestWork.png", "ComplexHonestWork.png", "ComplexDishonestWork.png"],

    options: ['Spain', 'France', 'Germany', 'Another country'],

    correct_answer: 2

  },

  {

    sentence: "You are on a health governing body deciding whether a new STD treatment, that affects straight couples, should be administered as a pill for men or a pill for women. Assuming effectiveness and risks are identical, and your goal is to maximize community protection based on the average number of sexual partners each gender has, which pill should you choose?",

    graph_pool: ["SimpleHonestSex.png", "SimpleDishonestSex.png", "ComplexHonestSex.png", "ComplexDishonestSex.png"],

    options: ['Pill for men', 'Pill for women', 'It is the same'],

    correct_answer: 2

  },

  {

    sentence: "You are planning your next holiday and deciding whether to visit Sydney or Perth. If your main goal is to minimize the chance of rain, which city should you choose?",

    graph_pool: ["SimpleHonestRain.png", "SimpleDishonestRain.png", "ComplexHonestRain.png", "ComplexDishonestRain.png"],

    options: ['Sydney', 'Perth', 'Not enough data'],

    correct_answer: 1

  }

];



for (let trial_data of experimental_trials) {



  // Step A: The Choice Stage

    const choice_trial = {

    type: jsPsychHtmlButtonResponse,

    stimulus: function() {

      const chosen_graph = jsPsych.randomization.sampleWithoutReplacement(trial_data.graph_pool, 1)[0];

      jsPsych.getCurrentTrial().data.selected_graph = chosen_graph;

  

      return `

      <div class="trial-text" style="font-weight: 600;">

        ${trial_data.sentence}

      </div>

      <div class="experiment-graph-container">

        <img src="${chosen_graph}" class="experiment-graph"/>

      </div>

      `;

    },

    choices: trial_data.options,

    data: {

      task_part: 'decision',

      correct_response: trial_data.correct_answer,

      sentence_presented: trial_data.sentence

    },

    on_finish: function(data) {

      data.is_correct = (data.response === data.correct_response) ? 1 : 0;

    }

  };



  // Step B: The Confidence Stage

  const confidence_trial = {

    type: jsPsychHtmlSliderResponse,

    stimulus: `<h3 style="font-size: 1.2rem; font-weight: 600; margin-bottom: 2rem; padding: 0 10px;">How confident are you in the decision you just made?</h3>`,

    labels: [

      '0%<br>(Guessing)',

      '25%',

      '50%',

      '75%',

      '100%<br>(Certain)'

    ],

    min: 0,

    max: 100,

    slider_start: 50,

    step: 5,

    data: {

      task_part: 'confidence',

      sentence_presented: trial_data.sentence

    },

    on_start: function(trial) {

      const last_trial_data = jsPsych.data.get().last(1).values()[0];

      trial.data.selected_graph = last_trial_data.selected_graph;

    }

  };



  timeline.push(choice_trial);

  timeline.push(confidence_trial);

}



const thank_you_trial = {

  type: jsPsychHtmlButtonResponse,

  stimulus: `

  <h2>Thank you for your participation!</h2>

  <p>Click below to proceed to the final feedback form.</p>

  `,

  choices: ['Go to form'],

  on_start: function() {

    if (typeof cognition_run_finish === "function") {

      cognition_run_finish();

    }

  },

  on_finish: function() {

    window.onbeforeunload = null;

    window.addEventListener('beforeunload', (event) => {

      event.stopImmediatePropagation();

    }, true);



    setTimeout(function() {

      window.location.href = "https://forms.gle/DPg2cgRAKfNwDBTU8";

    }, 300);

  }

};

timeline.push(thank_you_trial);



jsPsych.run(timeline);